[2023-07-30 12:48:24,025] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-22T19:01:19+00:00 [queued]>
[2023-07-30 12:48:24,217] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_user 2023-06-22T19:01:19+00:00 [queued]>
[2023-07-30 12:48:24,217] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-07-30 12:48:24,218] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-07-30 12:48:24,219] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-07-30 12:48:24,260] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): create_user> on 2023-06-22T19:01:19+00:00
[2023-07-30 12:48:24,264] {standard_task_runner.py:52} INFO - Started process 8362 to run task
[2023-07-30 12:48:24,275] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'create_user', '2023-06-22T19:01:19+00:00', '--job-id', '14263', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/test.py', '--cfg-path', '/tmp/tmp054tzsx7', '--error-file', '/tmp/tmp8imcwh4o']
[2023-07-30 12:48:24,276] {standard_task_runner.py:77} INFO - Job 14263: Subtask create_user
[2023-07-30 12:48:24,369] {logging_mixin.py:104} INFO - Running <TaskInstance: my_first_dag.create_user 2023-06-22T19:01:19+00:00 [running]> on host fd6918d9d7f3
[2023-07-30 12:48:24,873] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_user
AIRFLOW_CTX_EXECUTION_DATE=2023-06-22T19:01:19+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-22T19:01:19+00:00
[2023-07-30 12:48:24,876] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-07-30 12:48:24,877] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\nid -u test_user;\nif [$? -eq o];\n    then echo "User exists"\nelse sudo useradd -r test_user;\n    echo "User created";\nfi']
[2023-07-30 12:48:24,888] {subprocess.py:75} INFO - Output:
[2023-07-30 12:48:24,959] {subprocess.py:79} INFO - id: ‘test_user’: no such user
[2023-07-30 12:48:24,967] {subprocess.py:79} INFO - bash: line 2: [1: command not found
[2023-07-30 12:48:25,031] {subprocess.py:79} INFO - 
[2023-07-30 12:48:25,032] {subprocess.py:79} INFO - We trust you have received the usual lecture from the local System
[2023-07-30 12:48:25,032] {subprocess.py:79} INFO - Administrator. It usually boils down to these three things:
[2023-07-30 12:48:25,033] {subprocess.py:79} INFO - 
[2023-07-30 12:48:25,034] {subprocess.py:79} INFO -     #1) Respect the privacy of others.
[2023-07-30 12:48:25,034] {subprocess.py:79} INFO -     #2) Think before you type.
[2023-07-30 12:48:25,035] {subprocess.py:79} INFO -     #3) With great power comes great responsibility.
[2023-07-30 12:48:25,036] {subprocess.py:79} INFO - 
[2023-07-30 12:48:25,036] {subprocess.py:79} INFO - sudo: no tty present and no askpass program specified
[2023-07-30 12:48:25,043] {subprocess.py:79} INFO - User created
[2023-07-30 12:48:25,047] {subprocess.py:83} INFO - Command exited with return code 0
[2023-07-30 12:48:25,103] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_user, execution_date=20230622T190119, start_date=20230730T124824, end_date=20230730T124825
[2023-07-30 12:48:25,200] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-30 12:48:25,257] {local_task_job.py:151} INFO - Task exited with return code 0
